server:
  port: ${APP_PORT:8081}
  servlet:
    session:
      cookie:
        http-only: true
    context-path: /frilance
    application-display-name: Frilance
  tomcat:
    max-connections: 1000
    accept-count: 100
    connection-timeout: 30000

spring:
  application:
    name: frilance
  datasource:
    url: jdbc:postgresql://localhost:5432/frilance
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml

logging:
  level:
    ROOT: INFO
    ru.iteco.project: DEBUG
    org.springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
  metrics:
    export:
      atlas:
        enabled: true

  # Регулярное выражение для валидации электронной почты
user:
  email:
    regexp: '^([A-Za-z0-9._-]{1,40})@([A-Za-z0-9._-]{1,20}\.)([A-Za-z0-9._-]{1,15})$'


task:
  description:
    length:
      max: 1000 # Максимальное количество символов в названии задания
  decision:
    length:
      max: 100000 # Максимальное количество символов в решении задания
  price:
    min: 0  # Минимальная стоимость задания


format:
  date:
    time: yyyy-MM-dd HH:mm:ss # Установленный формат даты и времени
