spring:
  config:
    use-legacy-processing: true
  profiles:
    active: development
    include: swagger

logging:
  level:
    ru.iteco.project.service: INFO
  appenders:
    file:
      enabled: true
      name: log
      path: logs/auth
      maxHistory: 300
    console:
      enabled: true


# Настройки аудита
audit:
  logName: audit
  logPath: /audit
  maxHistory: 300
  destination: 'DB'