spring:
  config:
    use-legacy-processing: true
  profiles:
    active: local
    include: swagger

logging:
  level:
    ru.iteco.project.service: DEBUG
  appenders:
    file:
      enabled: true
      name: log
      path: logs/auth
      maxHistory: 300
    console:
      enabled: true

# Настройки аудита
audit:
  logName: audit
  logPath: /audit
  maxHistory: 300