spring:
  profiles:
    active: local
    include: swagger

logging:
  level:
    ru.iteco.project.service: DEBUG
  appenders:
    file:
      enabled: true
      name: log
      path: logs
      maxHistory: 300
    console:
      enabled: true
